external_components:
  - source:
      type: git
      url: https://github.com/AlteroAscension/esphome-dynamixel
      ref: main
    components: [dynamixel]

esphome:
  name: ar_id64_demo
  platform: ESP32
  board: esp32dev

logger:

uart:
  id: uart_dxl
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

dynamixel:
  id: dxl
  uart_id: uart_dxl
  protocol: 1
  direction_pin: 4
  devices:
    - name: "ar_id64"
      device_id: 64
      protocol: 1
      registers:
        - { name: "model_number", address: 0, length: 2, access: "r" }
        - { name: "firmware_version", address: 2, length: 1, access: "r" }
        - { name: "id", address: 3, length: 1, access: "rw" }
        - { name: "baud_rate", address: 4, length: 1, access: "rw" }
        - { name: "return_delay_time", address: 5, length: 1, access: "rw" }
        - { name: "out_voltage_v", address: 6, length: 1, access: "rw" }
        - { name: "vcl1_voltage_offset_mv_s", address: 9, length: 1, access: "rw" }
        - { name: "batt_voltage_offset_mv_s", address: 10, length: 1, access: "rw" }
        - { name: "out_current_offset_ma_s", address: 11, length: 2, access: "rw" }
        - { name: "undercurr_timeout_dis_flag_on_start", address: 13, length: 1, access: "rw" }
        - { name: "out_max_current_ma", address: 14, length: 2, access: "rw" }
        - { name: "undercurrent_timeout_s", address: 16, length: 2, access: "rw" }
        - { name: "batt_level", address: 20, length: 1, access: "rw" }
        - { name: "reset_trigger", address: 23, length: 1, access: "rw" }
        - { name: "undercurr_timeout_dis_flag", address: 24, length: 1, access: "w" }
        - { name: "out_current_ma", address: 26, length: 2, access: "r" }
        - { name: "registered", address: 29, length: 1, access: "r" }
        - { name: "batt_voltage_mv", address: 30, length: 2, access: "r" }
        - { name: "vcl1_voltage_mv", address: 32, length: 2, access: "r" }
        - { name: "vcl2_voltage_mv", address: 34, length: 2, access: "r" }
        - { name: "fault_and_stat", address: 36, length: 1, access: "r" }

switch:
  - platform: dynamixel
    name: "AR_ID64 Undercurrent Timeout Disable"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "undercurr_timeout_dis_flag_on_start"

  - platform: dynamixel
    name: "AR_ID64 Reset Trigger"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "reset_trigger"

  - platform: dynamixel
    name: "AR_ID64 Undercurrent Timeout Disable (runtime)"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "undercurr_timeout_dis_flag"

select:
  - platform: dynamixel
    name: "AR_ID64 Output Voltage"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "out_voltage_v"
    options:
      - { name: "9V", value: 9 }
      - { name: "12V", value: 12 }

number:
  - platform: dynamixel
    name: "AR_ID64 Battery Level"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "batt_level"
    min_value: 0
    max_value: 100
    step: 1

  - platform: dynamixel
    name: "AR_ID64 Max Output Current (mA)"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "out_max_current_ma"
    min_value: 1000
    max_value: 5000
    step: 10

  - platform: dynamixel
    name: "AR_ID64 Undercurrent Timeout (s)"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "undercurrent_timeout_s"
    min_value: 20
    max_value: 3600
    step: 1

sensor:
  - platform: dynamixel
    name: "AR_ID64 Firmware Version"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "firmware_version"
    update_interval: 30s

  - platform: dynamixel
    name: "AR_ID64 Model Number"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "model_number"
    update_interval: 30s

  - platform: dynamixel
    name: "AR_ID64 Output Current"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "out_current_ma"
    update_interval: 1s
    signed: true
    unit_of_measurement: "mA"

  - platform: dynamixel
    name: "AR_ID64 Battery Voltage"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "batt_voltage_mv"
    update_interval: 1s
    unit_of_measurement: "mV"

  - platform: dynamixel
    name: "AR_ID64 VCL1 Voltage"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "vcl1_voltage_mv"
    update_interval: 1s
    unit_of_measurement: "mV"

  - platform: dynamixel
    name: "AR_ID64 VCL2 Voltage"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "vcl2_voltage_mv"
    update_interval: 1s
    unit_of_measurement: "mV"

  - platform: dynamixel
    name: "AR_ID64 Fault/Status"
    dynamixel_id: dxl
    dxl_device_id: 64
    register: "fault_and_stat"
    update_interval: 1s
