external_components:
  - source:
      type: git
      url: https://github.com/yourname/esphome-dynamixel
      ref: main
    components: [dynamixel]

esphome:
  name: dynamixel_demo
  platform: ESP32
  board: esp32dev

logger:

uart:
  id: uart_dxl
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

dynamixel:
  id: dxl
  uart_id: uart_dxl
  protocol: 2
  direction_pin: 4
  devices:
    - name: "xm430"
      device_id: 1
      protocol: 2
      registers:
        - { name: "torque_enable", address: 64, length: 1, access: "rw" }
        - { name: "goal_position", address: 116, length: 4, access: "rw" }
        - { name: "present_position", address: 132, length: 4, access: "r" }
