external_components:
  - source:
      type: github
      repository: AlteroAscension/esphome-dynamixel
      ref: main
    components: [dynamixel]

esphome:
  name: xm430_demo
  platform: ESP32
  board: esp32dev

logger:

uart:
  id: uart_dxl
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600

dynamixel:
  id: dxl
  uart_id: uart_dxl
  protocol: 2
  direction_pin: 4
  devices:
    - name: "xm430"
      device_id: 1
      protocol: 2
      registers:
        - { name: "operating_mode", address: 11, length: 1, access: "rw" }
        - { name: "torque_enable", address: 64, length: 1, access: "rw" }
        - { name: "led", address: 65, length: 1, access: "rw" }
        - { name: "velocity_limit", address: 44, length: 4, access: "rw" }
        - { name: "profile_acceleration", address: 108, length: 4, access: "rw" }
        - { name: "profile_velocity", address: 112, length: 4, access: "rw" }
        - { name: "goal_velocity", address: 104, length: 4, access: "rw" }
        - { name: "goal_position", address: 116, length: 4, access: "rw" }
        - { name: "present_velocity", address: 128, length: 4, access: "r" }
        - { name: "present_position", address: 132, length: 4, access: "r" }
        - { name: "position_d_gain", address: 80, length: 2, access: "rw" }
        - { name: "position_i_gain", address: 82, length: 2, access: "rw" }
        - { name: "position_p_gain", address: 84, length: 2, access: "rw" }
